apiVersion: cps1.tech/v1alpha1
kind: Resource
metadata:
  name: mariadb
spec:
  name: mariadb
  label: MariaDB
  icon: mariadb.svg
  description: >-
    MariaDB is a free, open-source relational database management system (RDBMS)
    developed by the original creators of MySQL. It's designed to be fast,
    reliable, and user-friendly, suitable for both small and large-scale data processing. 
  versions:
    - name: "10.5"
      image: "mariadb:10.5"
    - name: "10.6"
      image: "mariadb:10.6"
    - name: "10.11"
      image: "mariadb:10.11"
    - name: "11.4"
      image: "mariadb:11.4"
    - name: "11.7"
      image: "mariadb:11.7"
  properties:
    - name: root_password
      label: Root password
      tip: Password for the root user
      required: false
      default: root
      env: MARIADB_ROOT_PASSWORD
      kind: secret
  defaults:
    env:
      - name: VAR
        value: var
    ports:
      - exposure: internal
        protocol: tcp
        port: 3306
    volumes:
      - name: datadir
        path: /var/lib/mysql
    limits:
      memory: 512
      cpu: 1
