apiVersion: cps1.tech/v1alpha1
kind: CPS1Resource
metadata:
  name: mongodb
spec:
  name: mongodb
  label: MongoDB
  icon: mongodb.svg
  description: >-
    MongoDB is a NoSQL document database that stores data in a flexible,
    JSON-like format. It's designed for modern application development and
    cloud environments, offering scalability, flexibility, and ease of use for developers.
  versions:
    - name: "10.5"
      image: "mariadb:10.5"
  properties:
    - name: root_password
      label: Root password
      tip: Password for the root user
      required: false
      default: root
      env: ROOT_PASSWORD
      kind: secret
  defaults:
    ports:
      - exposure: internal
        protocol: tcp
        port: 3366
    env:
      - name: PGDATA
        value: /var/lib/postgresql/data/pgdata
    volumes:
      - name: pgdata
        path: /var/lib/postgresql/data
    limits:
      memory: 512
      cpu: 1
